"""Weights & Biases (wandb) integration for experiment tracking.

Provides optional wandb logging for training runs with graceful fallback,
automatic environment configuration, and comprehensive metric tracking.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any
import wandb


def load_env_file(env_path: Path | str | None = None) -> None:
    """Load environment variables from .env file.

    Args:
        env_path: Path to .env file (default: project_root/.env)
    """
    if env_path is None:
        current_path = Path(__file__).resolve()
        for parent_dir in [current_path, *current_path.parents]:
            if (parent_dir / "pyproject.toml").exists():
                env_path = parent_dir / ".env"
                break

    env_path = Path(env_path)
    if not env_path.exists():
        return

    with open(env_path) as env_file:
        for line in env_file:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            if '=' in line:
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip()
                if key not in os.environ:
                    os.environ[key] = value


class WandbLogger:
    """Wrapper for Weights & Biases logging with graceful fallback.

    Auto-loads API key from .env file, falls back gracefully if wandb not installed,
    and integrates with TrainingLogger for unified logging.

    Args:
        project: Project name (default: from WANDB_PROJECT env or "cs336-assignment1")
        entity: Team/entity name (default: from WANDB_ENTITY env or None)
        name: Run name (default: auto-generated by wandb)
        config: Hyperparameters to track
        tags: Tags for organizing runs
        enabled: Enable wandb logging (default: True)

    Example:
        >>> with WandbLogger(project="my-project", config={"learning_rate": 0.001}) as logger:
        >>>     logger.log({"loss": 0.5, "accuracy": 0.95}, step=100)
    """

    def __init__(
        self,
        project: str | None = None,
        entity: str | None = None,
        name: str | None = None,
        config: dict[str, Any] | None = None,
        tags: list[str] | None = None,
        enabled: bool = True
    ) -> None:
        self.enabled = enabled
        self.wandb = None
        self.run = None

        if not enabled:
            return

        load_env_file()

        if os.getenv("WANDB_DISABLED", "").lower() == "true":
            self.enabled = False
            return

        try:
            self.wandb = wandb
        except ImportError:
            print("⚠️  wandb not installed. Install with: pip install wandb")
            print("   Continuing without wandb logging...")
            self.enabled = False
            return

        api_key = os.getenv("WANDB_API_KEY")
        if api_key:
            try:
                wandb.login(key=api_key, relogin=True)
            except Exception as auth_error:
                print(f"⚠️  wandb authentication failed: {auth_error}")
                print("   Continuing without wandb logging...")
                self.enabled = False
                return

        project = project or os.getenv("WANDB_PROJECT", "cs336-assignment1")
        entity = entity or os.getenv("WANDB_ENTITY")

        try:
            self.run = self.wandb.init(
                project=project,
                entity=entity,
                name=name,
                config=config or {},
                tags=tags or [],
                reinit=True
            )
            print(f"✓ wandb initialized: {self.run.url}")
        except Exception as init_error:
            print(f"⚠️  Failed to initialize wandb: {init_error}")
            print("   Continuing without wandb logging...")
            self.enabled = False

    def log(self, metrics: dict[str, Any], step: int | None = None, commit: bool = True) -> None:
        """Log metrics to wandb.

        Args:
            metrics: Metric names and values (e.g., {"loss": 0.5, "accuracy": 0.95})
            step: Step number for x-axis (default: auto-incremented)
            commit: Commit immediately (default: True)
        """
        if not self.enabled or self.run is None:
            return

        try:
            self.wandb.log(metrics, step=step, commit=commit)
        except Exception as log_error:
            print(f"⚠️  wandb logging failed: {log_error}")

    def log_hyperparameters(self, config: dict[str, Any]) -> None:
        """Log or update hyperparameters.

        Args:
            config: Hyperparameter names and values
        """
        if not self.enabled or self.run is None:
            return

        try:
            self.wandb.config.update(config)
        except Exception as config_error:
            print(f"⚠️  wandb config update failed: {config_error}")

    def log_artifact(
        self,
        artifact_path: str | Path,
        artifact_name: str,
        artifact_type: str = "model"
    ) -> None:
        """Log a file or directory as a wandb artifact.

        Args:
            artifact_path: Path to file or directory
            artifact_name: Artifact name
            artifact_type: Artifact type ("model", "dataset", "vocab", etc.)
        """
        if not self.enabled or self.run is None:
            return

        try:
            artifact = self.wandb.Artifact(artifact_name, type=artifact_type)
            artifact.add_file(str(artifact_path))
            self.run.log_artifact(artifact)
        except Exception as artifact_error:
            print(f"⚠️  wandb artifact logging failed: {artifact_error}")

    def watch_model(self, model: Any, log_frequency: int = 100) -> None:
        """Watch a PyTorch model for gradients and parameters.

        Args:
            model: PyTorch model to watch
            log_frequency: Logging frequency in steps
        """
        if not self.enabled or self.run is None:
            return

        try:
            self.wandb.watch(model, log="all", log_freq=log_frequency)
        except Exception as watch_error:
            print(f"⚠️  wandb model watching failed: {watch_error}")

    def finish(self) -> None:
        """Finish the wandb run and upload final data."""
        if not self.enabled or self.run is None:
            return

        try:
            self.wandb.finish()
            print("✓ wandb run finished")
        except Exception as finish_error:
            print(f"⚠️  wandb finish failed: {finish_error}")

    def __enter__(self) -> 'WandbLogger':
        """Context manager entry."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        """Context manager exit - automatically finish run."""
        self.finish()

    @property
    def url(self) -> str | None:
        """Get the wandb run URL."""
        if self.run is not None:
            return self.run.url
        return None


def is_wandb_available() -> bool:
    """Check if wandb is installed.

    Returns:
        True if wandb is available, False otherwise
    """
    try:
        import wandb
        return True
    except ImportError:
        return False